name: inventorypos
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^27.2.4
  window_size: ^0.1.0
  currency_text_input_formatter: ^2.2.6
  supabase_flutter: ^2.8.1
  internet_connection_checker_plus: ^2.5.2
  provider: ^6.1.2
  sqflite_common_ffi: ^2.3.4+3
  fluttertoast: ^8.2.8
  overlay_support: ^2.1.0
  file_picker: ^8.1.4
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/image/
